### ISSUE TITLE
cov.npy is loaded even when the run is new

### ISSUE THREAD

**Issue by AaronDJohnson** [nanograv/enterprise_extensions#174]
If the file exists, the sample covariance matrix (cov.npy) is loaded regardless of whether it actually corresponds to the run that is requested. This leads to index errors when the covariance matrix doesn't have the same shape as the new run.

A quick fix would require `resume=True` and check the shape of the matrices

There is a remaining corner case though: If someone uses the same number, but different pulsars we could end up still loading the cov.npy file instead of creating a new one.

**Comment by Hazboun6** [comment]
Personally, I think the quick fix is pretty good. 

The issue you are pointing out with the parameter space being the same size would also be an issue with the chains themselves. That comes down to an issue with the way that `PTMCMCSampler` does things, since it does absolutely no checking of chains or anything. 

If we wanted to do this type of checking, then we could check against the priors.txt file, or even more explicitly the model that is printed out in the run report. That would take a bit more coding though. 

(Also, I at least take advantage of the default overwriting in a lot of my workflow. As you mentioned Aaron we could use another `overwrite` flag, but that starts to get cumbersome.)

@kdolum and @paulthebaker do you have any thoughts on this?

**Comment by kdolum** [comment]
If resume=False, we should certainly not read old files.  If the person sets resume=True, but the directory is actually from a different run, we cannot always protect them from this mistake.  I think it would be worth checking the size so as to have a comprehensible error instead of a mysterious index problem, but I don't think it's necessary to go beyond that.  It might generally be worth printing a message when resuming just to say what is happening.
I don't know how people generally use resume.  Personally, I only set it when I am actually resuming.  Thus I would favor a plan where resume=True gives an error unless there is a run to resume.  This would discourage setting this flag always, which would in turn discourage resuming from an unrelated run.  Other hand, maybe people would lose their work by restarting runs they'd meant to resume, so this could be a bad idea.

**Comment by Hazboun6** [comment]
Fixed with PR #175
